language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+$/
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y tree
  - npm install
script:
  - npm run test
  - npm run build
  - tree src
  - git log