language: node_js
node_js:
  - 12.13.0
  - 8.16.2
  - 13.1.0
cache: npm
branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+$/
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y tree
  - npm install
script:
  - npm run test
  - npm run build
  - tree src
  - git log
jobs:
  include:
    - language: python
      python: 3.6
      script:
      - python -c "print('Hi from Python!')"
    - language: node_js
      node_js: 9
      script:
      - node -e "console.log('Hi from NodeJS!')"
    - language: java
      jdk: openjdk8
      script:
      - javac -help